services:
  streamlit:
    container_name: "RAG_eco_reports"
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '8080:8080'
    command: streamlit run main.py --server.port=8080 --server.address=0.0.0.0
